<script setup>
// Hero Data
const heroData = {
  eyebrow: 'Our Footprint',
  titleMain: 'Travel That Leaves A',
  titleItalic: 'Place Better.',
  intro: 'A deliberate commitment to protecting the landscapes we traverse and empowering the local communities that host us.',
  bgImage: '/images/home/itin-1.jpg'
}

// Intro Center Data
const introData = {
  eyebrow: 'Core Ethos',
  titleMain: 'Meaningful',
  titleHighlight: 'Reciprocity.',
  paragraph: 'True luxury is not defined by excess, but by intention. We architect journeys that actively give back, ensuring that the economic and cultural wealth generated by tourism remains firmly rooted in the communities that create it.'
}

// Banner Data
const bannerData = {
  title: 'Join us in shaping journeys that create lasting, positive change.',
  buttonText: 'Plan Your Route',
  buttonUrl: '/planyourjourney',
  images: [
    '/images/home/stay-1.jpeg',
    '/images/home/stay-2.jpeg',
    '/images/home/stay-3.jpg'
  ]
}
</script>

<template>
  <main class="page-container w-full bg-[#F9F8F6] overflow-hidden">
    
    <!-- 1. Hero Header -->
    <HeroInner :hero-data="heroData" />

    <!-- 2. Intro Center -->
    <IntroInnerCenter :data="introData" />

    <!-- 3. Impact Main Content Component -->
    <ImpactInner />

    <!-- 4. Related Posts Modular Component (Uses default payload automatically) -->
    <RelatedPosts 
      eyebrow="Further Reading" 
      title-main="Related" 
      title-highlight="Stories." 
    />

    <!-- 5. Bottom Banner -->
    <Banner :banner-data="bannerData" />

  </main>
</template>